Connect bd
QuewarG/Auto-Manager pull request #6
Opened 2023-10-18 14:44 UTC by OviedoSebastian

2023-10-18 15:00 UTC, OviedoSebastian reviewed
Este es el que se debe de aprobar

2023-10-25 13:47 UTC, QuewarG reviewed
Esta sobre la rama que no es.

2023-11-15 21:29 UTC, QuewarG requested changes
Genera conflictos

2023-11-15 21:29 UTC, QuewarG commented
Genera conflictos

2023-11-15 21:29 UTC, closed without merging